SET(TUHHSDK_SRCS 
	tuhhsdk/src/tuhh.cpp
	tuhhsdk/src/tuhh.h
	tuhhsdk/src/Tools/DcmConverter.h
	tuhhsdk/src/Tools/Var/Command.h
	tuhhsdk/src/Tools/Storage/Blackboard.h
	tuhhsdk/src/Tools/Storage/Blackboard.cpp
	tuhhsdk/src/Tools/Math/KalmanFilter.h
	tuhhsdk/src/Tools/Math/KalmanFilter.cpp
	tuhhsdk/src/Tools/Math/Matrix2x2.h
	tuhhsdk/src/Tools/Math/Matrix3x3.h
	tuhhsdk/src/Tools/Math/RotationMatrix.h
	tuhhsdk/src/Tools/Math/Vector2.h
	tuhhsdk/src/Tools/Math/Vector3.h
	tuhhsdk/src/Tools/Kinematics/Com.h
	tuhhsdk/src/Tools/Kinematics/Com.cpp
	tuhhsdk/src/Tools/Kinematics/ForwardKinematics.h
	tuhhsdk/src/Tools/Kinematics/ForwardKinematics.cpp
	tuhhsdk/src/Tools/Kinematics/InverseKinematics.h
	tuhhsdk/src/Tools/Kinematics/InverseKinematics.cpp
	tuhhsdk/src/Tools/Kinematics/KinematicMatrix.h
	tuhhsdk/src/Modules/Alias.h
	tuhhsdk/src/Modules/Alias.cpp
	tuhhsdk/src/Modules/DcmConnector.h
	tuhhsdk/src/Modules/DcmConnector.cpp
	tuhhsdk/src/Modules/DcmEngine.h
	tuhhsdk/src/Modules/DcmEngine.cpp
	tuhhsdk/src/Modules/MotionPlayer.h
	tuhhsdk/src/Modules/MotionPlayer.cpp
	tuhhsdk/src/Modules/Poses.h
	tuhhsdk/src/Modules/Poses.cpp
	tuhhsdk/src/Definitions/keys.h
	tuhhsdk/src/Definitions/keys.cpp
	tuhhsdk/src/Definitions/robotConstants.h
	tuhhsdk/src/Definitions/robotConstants.cpp	
	)
